version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
    reviewers:
      - lithiumtoast
    target-branch: main
