name: "bindgen"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SDK_VERSION: 6.0.x

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:

  bindgen-job:
    name: "Bindgen"
    runs-on: ubuntu-latest
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        submodules: 'true'

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_SDK_VERSION }}'
        include-prerelease: true

    - name: "Install C2CS"
      shell: bash
      run: dotnet tool install c2cs --global --add-source https://www.myget.org/F/bottlenoselabs/api/v3/index.json --version "*-*"

    - name: "bindgen"
      shell: bash
      run: ./bindgen.sh

    - name: "Upload bindgen results"
      uses: actions/upload-artifact@v2
      with:
        name: bindgen-results
        path: src/cs/production/SDL-cs/SDL.cs