name: "bindgen"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SDK_VERSION: 6.0.x

on:
  workflow_run:
    workflows: ["pr"]
    types:
      - completed

jobs:
  bindgen-job:
    name: "bindgen"
    runs-on: ubuntu-latest
    steps:

      - name: "Update check"
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "bindgen"
          status: in_progress

      - name: "Clone Git repository"
        uses: actions/checkout@master
        with:
          submodules: 'true'
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: "Install .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{ env.DOTNET_SDK_VERSION }}'
          include-prerelease: true

      - name: "Install C2CS"
        shell: bash
        run: dotnet tool install bottlenoselabs.C2CS --global --add-source https://www.myget.org/F/bottlenoselabs/api/v3/index.json --version "*-*"

      - name: "bindgen"
        shell: bash
        run: ./bindgen.sh

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@v7
        with:
          default_author: user_info
          message: "Update bindings"
          branch: ${{ github.event.workflow_run.head_sha }}"
    
      - name: "Update check"
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "bindgen"
          status: completed
          conclusion: ${{ job.status }}