name: "Bindgen"
on:
  push:
    branches: [develop]
    paths: ['ext/SDL/**']


jobs:

  bindgen:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        submodules: true

    - name: "Bindgen (Unix)"
      if: matrix.os != 'windows-latest'
      shell: bash
      run: ./bindgen.sh

    - name: "Bindgen (Windows)"
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: .\bindgen.cmd

    - name: "Add + commit + push (if necessary)"
      uses: EndBug/add-and-commit@v7
      with:
        default_author: user_info