name: "bindgen"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SDK_VERSION: 6.0.x

on:
  pull_request_target

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - '**.yml'
    branches:
      - 'dependabot/submodules/ext/SDL-*'

jobs:
  dependabot-job:
    name: "dependabot"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        submodules: 'true'

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_SDK_VERSION }}'
        include-prerelease: true

    - name: "Install C2CS"
      shell: bash
      run: dotnet tool install c2cs --global --add-source https://www.myget.org/F/bottlenoselabs/api/v3/index.json --version "*-*"

    - name: "bindgen"
      shell: bash
      run: ./bindgen.sh

    - name: "Add + commit + push (if necessary)"
      uses: EndBug/add-and-commit@v7
      with:
        default_author: user_info
        message: "Update bindings"

  