name: "pr"

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - '**.md'

jobs:
  bindgen-job:
    name: "bindgen"
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@master
        with:
          submodules: 'true'

      - name: "Install .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: "Install C2CS"
        shell: bash
        run: dotnet tool install bottlenoselabs.C2CS --global --add-source https://www.myget.org/F/bottlenoselabs/api/v3/index.json --version "*-*"

      - name: "bindgen"
        shell: bash
        run: ./bindgen.sh

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@v7
        with:
          default_author: user_info
          message: "Update bindings"
  