name: Set workflow status

on:
  workflow_run:
    workflows:
      - "devops"
    types:
      - completed

jobs:
  set_status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write 
    steps:
      - name: "Set status"
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "${{ github.event.workflow_run.name }} (${{ github.event.workflow_run.event}})",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail